name: deployment

on:
  workflow_dispatch:
    branches:
      - main

env:
  SSH_KEY: ${{ secrets.SSH_KEY }}
  TF_VAR_github_token: ${{ secrets.GITHUB_TOKEN }}
  TF_VAR_db_password: ${{ secrets.DB_PASSWORD }}
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_REGION: ap-northeast-1

jobs:
  deployment:
    runs-on: ubuntu-latest
    environment: main
    steps:
      - uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
            terraform_version: 1.8.2

      - name: Generate Key
        run: ./scripts/keygen.sh

      - name: Terraform init and validate
        run: terraform init

      - name: Terraform plan
        run: terraform plan
